language: r
r:
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - devel
os:
  - linux
  - osx
  - windows
jobs:
  exclude:
  - r: 3.2
    os: osx
  - r: 3.3
    os: osx
after_success:
    - Rscript -e 'covr::codecov()'

