language: r
sudo: false
dist: trusty
cache: packages
fortran: false
install:
- R -e 'devtools::install_deps(dep = T)'
jobs:
  include:
  - r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("tidyverse/tidytemplate")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE)'
      skip_cleanup: true
buildtests:
  - R CMD build .
  - R CMD check *tar.gz



env:
  global:
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_SYSTEM_CLOCK_=FALSE
