# codecov:
#   strict_yaml_branch: master

comment: false

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 1%


